neo:
  prod

rate-limit-by-ip-filter:
  capacity: 10
  refill-tokens: 1
  amount: 1
  unit: SECONDS
  cpu-max-usage: 0.5

security:
  server:
    username: admin
    password: passwd
  client:
    username: admin
    password: passwd
    
